### ISSUE TITLE
Include details for setting up via anaconda

### ISSUE THREAD

**Issue by aezarebski** [aezarebski/aas-extended-examples#48]
Given that anaconda is used elsewhere in the course, further use of this as a manager may be easier than other methods.

**Comment by aezarebski** [comment]
There is now a section in `setup.org` that should point to anaconda installation instructions: https://github.com/aezarebski/aas-extended-examples/blob/main/setup.org#anaconda

**Comment by am-bean** [comment]
I think in the section on venvs you can simply call `pip install requirements.txt`

**Comment by aezarebski** [comment]
Yep, with `-r`, I'll this to split the notes into a "how the venv is built from scratch" and "how a user can build it", the former is good to keep handy in case something breaks down the line and we need to fix it. Are you happy to put in a note about the anaconda bit?

**Comment by am-bean** [comment]
Yes, I'll take a look at how Anaconda has been described elsewhere in the programme

**Comment by am-bean** [comment]
@aezarebski - Closing this. I've added text on Anaconda and split the venv notes
