### ISSUE TITLE
Renumber folders to whole numbers and use descriptive titles

### ISSUE THREAD

**Issue by am-bean** [aezarebski/aas-extended-examples#49]
As in title

**Comment by aezarebski** [comment]
Might be a good idea to do this as we progress through the weeks so we know exactly what to include. Definitely ugly, but probably simpler.

**Comment by aezarebski** [comment]
Perhaps we could keep the current naming system and add a section like the following to the `README.org`

```

* Contents

- [[https://github.com/aezarebski/aas-extended-examples/tree/main/example-0][Example 0]] contains an overview of the software packages we will be using and
  basic python skills (primarily plotting with matplotlib).
- The [[https://github.com/aezarebski/aas-extended-examples/blob/main/setup.org][setup]] page gives some instructions for setting up the software and
  notebooks.

```

which will render as 

**Contents**

- [Example 0](https://github.com/aezarebski/aas-extended-examples/tree/main/example-0) contains ...
- The [setup](https://github.com/aezarebski/aas-extended-examples/blob/main/setup.org) page ...

this is a safer approach for the reasons described in [this issue](https://github.com/aezarebski/aas-extended-examples/issues/52)

**Comment by aezarebski** [comment]
Closing this because we have a way to address this now.
