### ISSUE TITLE
there are white spaces in file/directory names

### ISSUE THREAD

**Issue by aezarebski** [aezarebski/aas-extended-examples#52]
Because these files are to be used across different operating systems the use of white spaces in file and directory names is a recipe for trouble. Please use hyphens or underscores if you want to separate words. Also, the use of periods for anything other than to separate file extensions is sub-optimal as this can cause issues for some parsers trying to extract file types.

**Comment by am-bean** [comment]
I reverted the renames

**Comment by aezarebski** [comment]
Thanks @am-bean, sorry, I should have mentioned this earlier. The notebooks are looking good!
