### ISSUE TITLE
unnecessary and potentially confusing use of pandas in this snippet

### ISSUE THREAD

**Issue by aezarebski** [aezarebski/aas-extended-examples#57]
https://github.com/aezarebski/aas-extended-examples/blob/629a3e0a997b3e94b6faa8c91bf3565e51db2582/example-1/example-1-answers.md?plain=1#L102

unnecessary and potentially confusing use of pandas in this snippet, probably easier just to use vanilla list comprehensions and some extra variables.

**Comment by am-bean** [comment]
Looks like this is resolved as well
